// <auto-generated />
using System;
using Depitest.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Depitest.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251025205552_AddingDefualtValuesToDB1")]
    partial class AddingDefualtValuesToDB1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Depitest.Model.Categoray", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jewelery"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Men's Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Women's Clothing"
                        });
                });

            modelBuilder.Entity("Depitest.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategorayId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorayId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Good Laptop",
                            ImageAddress = "",
                            Name = "Laptop",
                            Price = 1000m,
                            quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Good Phone",
                            ImageAddress = "",
                            Name = "Phone",
                            Price = 500m,
                            quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Good Headphone",
                            ImageAddress = "",
                            Name = "Headphone",
                            Price = 200m,
                            quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Good Mouse",
                            ImageAddress = "",
                            Name = "Mouse",
                            Price = 100m,
                            quantity = 2
                        });
                });

            modelBuilder.Entity("Depitest.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            Password = "123123",
                            UserName = "Mahmoud"
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = true,
                            Password = "123456",
                            UserName = "Ahmed"
                        },
                        new
                        {
                            Id = 3,
                            IsAdmin = true,
                            Password = "123456789",
                            UserName = "Goda"
                        },
                        new
                        {
                            Id = 4,
                            IsAdmin = false,
                            Password = "123456sdsd",
                            UserName = "Yosif"
                        },
                        new
                        {
                            Id = 5,
                            IsAdmin = false,
                            Password = "123456sdsdfdd",
                            UserName = "Yosif123"
                        },
                        new
                        {
                            Id = 6,
                            IsAdmin = false,
                            Password = "123456sdsdfdd",
                            UserName = "Yosif455"
                        });
                });

            modelBuilder.Entity("Depitest.Model.Product", b =>
                {
                    b.HasOne("Depitest.Model.Categoray", "Categoray")
                        .WithMany()
                        .HasForeignKey("CategorayId");

                    b.Navigation("Categoray");
                });
#pragma warning restore 612, 618
        }
    }
}
